services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm install && npm run build
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
    # Let Render assign the port dynamically
    # Don't set a fixed port as Render needs to manage this 