services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
    # Let Render assign the port dynamically
    # Don't set a fixed port as Render needs to manage this 